### PR TITLE
Add slider

### PR DESCRIPTION
**Pull request by marwahaha**
Hi @ynasser ! 

I watched a [recording of your !!Con talk](https://www.youtube.com/watch?v=ld4gpQnaziU) and got inspired. These geometric patterns are beautiful!

I added a slider to your page. If you click the slider, you can use the arrow keys to adjust the angle (hold one arrow key for a "moving picture" effect!

Hope this is ok with you! 😃

### CODE REVIEW

**Comment by marwahaha** [comment]
By the way, I made the slider's range from 0°-180°. The previous instructions said to use a number between 0° and 90°, but there are some incredible patterns that happen at other theta values. (For example, tiling 4-6-12 with θ=98° .) After 180° I think the patterns repeat themselves on all 3 tilings.

**Comment by ynasser** [comment]
Thanks for the PR @marwahaha! It's true that the patterns past 90° look cool, but I think that's actually because I implemented the algorithm wrong when I did this years ago. I'll merge your changes and add a note about this soon :)

**Comment by marwahaha** [comment]
Thanks!

I'm not sure what happened, but for some reason the commit ([ab1eff6](https://github.com/ynasser/ynasser.github.io/commit/ab1eff6e32b575b3d846907a3550a26f03f1fc41)) didn't end up [on your master branch](https://github.com/ynasser/ynasser.github.io/commits/master).

I think you can run `git cherry-pick ab1eff6` to get it back! 🎈

**Comment by ynasser** [comment]
Ah yeah, I accidentally over-wrote some history. Should be fixed :)

**Pull request merged**
